### ISSUE TITLE
Fails on 7.2 Centos Install

### ISSUE THREAD

**Issue by monk-ee** [kemra102/puppet-cloudwatchlogs#15]
The plugin fails to correctly install the init script on Centos 7.2. It also fails to correctly install the awslogs-agent-launcher.sh.

This seems more to do with the python installer provided by AWS than with the puppet module.

My workaround was to puppet these two files on after the install, but moving forward this is probably not the best solution.

**Comment by kemra102** [comment]
Hi @monk-ee is this issue still persisting?

**Comment by xdexter** [comment]
Hello @kemra102,

I had have with the same problem in module version 2.1.0, so i updated to version 2.3.0 and removed awslogs, run puppet agent again and all works!

Thank you
