### ISSUE TITLE
Params present in github, but not in forge (log_level, logging_config_file)

### ISSUE THREAD

**Issue by flyinbutrs** [kemra102/puppet-cloudwatchlogs#19]
Hey,

Not exactly sure how this happened, but I installed this module via the forge, got v2.2.1, but this is the declaration for init.pp:

````puppet
class cloudwatchlogs (
  $state_file = $::cloudwatchlogs::params::state_file,
  $region     = $::cloudwatchlogs::params::region,
  $logs       = {}
) inherits cloudwatchlogs::params {
````

This is the top of it in github:

````puppet
class cloudwatchlogs (
  $state_file           = $::cloudwatchlogs::params::state_file,
  $logging_config_file  = $::cloudwatchlogs::params::logging_config_file,
  $region               = $::cloudwatchlogs::params::region,
  $log_level            = $::cloudwatchlogs::params::log_level,
  $logs                 = {}
) inherits cloudwatchlogs::params {
````

Not sure how things get published or how this disconnect happened...  any chance for a fix? I'd rather not have to install it via git.

Thanks,

-Dan

**Comment by kemra102** [comment]
Also not sure how things got out of sync, I'm behind on releases for this module anyway so I'll add it to my to do list for this evening to sort it all out and get it up on the Forge.

**Comment by kemra102** [comment]
@flyinbutrs Hopefully this is what you're looking for: https://forge.puppet.com/kemra102/cloudwatchlogs/readme

**Comment by flyinbutrs** [comment]
Yup, works now, thanks!
