### ISSUE TITLE
Updating module versions causes various failures

### ISSUE THREAD

**Issue by flyinbutrs** [kemra102/puppet-cloudwatchlogs#21]
[These lines](https://github.com/kemra102/puppet-cloudwatchlogs/blob/master/manifests/init.pp#L142-L145):

``` puppet
      file { '/var/awslogs/etc/config':
        ensure => 'link',
        target => '/etc/awslogs/config',
      }
```

result in this error when updating from a previous version of this module:

```
Notice: /Stage[main]/Cloudwatchlogs/File[/var/awslogs/etc/config]: Not removing directory; use 'force' to override
Notice: /Stage[main]/Cloudwatchlogs/File[/var/awslogs/etc/config]: Not removing directory; use 'force' to override
Error: Could not remove existing file
Error: /Stage[main]/Cloudwatchlogs/File[/var/awslogs/etc/config]/ensure: change from directory to link failed: Could not remove existing file
```

After fixing that, I then had another error:

[This require](https://github.com/kemra102/puppet-cloudwatchlogs/blob/e34e998cc2969103778fd106ff189719d1e48981/manifests/init.pp#L186) and [this one](https://github.com/kemra102/puppet-cloudwatchlogs/blob/e34e998cc2969103778fd106ff189719d1e48981/manifests/compartment_log.pp#L33) are only valid on amazon linux, as on other OS's, there is no Package['awslogs']. I've replaced it with a variable that's set based on OS.
#20

**Comment by c22** [comment]
Looks like PR #20 was merged in, @kemra102 any chance we can get an updated release on Puppet Forge?

**Comment by kemra102** [comment]
Done, apologies for the significant delay.
