### ISSUE TITLE
How to configure IAM user

### ISSUE THREAD

**Issue by xdexter** [kemra102/puppet-cloudwatchlogs#8]
Hello,

I can not understand how the issue of IAM user, wish I could set up a specific User for this service, and that he was not the default of cli aws, is this possible?

Att

**Comment by kemra102** [comment]
Hi,

I assume you're asking about setting up an IAM user/role, that is out of scope for this module (as per the modules readme) as such I'll close this issue.

Here are some links that might help though:

* http://docs.aws.amazon.com/IAM/latest/UserGuide/Using_SettingUpUser.html
* http://docs.aws.amazon.com/IAM/latest/UserGuide/roles-creatingrole.html
* https://github.com/kemra102/puppet-cloudwatchlogs/blob/master/README.md#setup-requirements

**Comment by xdexter** [comment]
hm Ok, thank you
