### ISSUE TITLE
How do I specify the log group?

### ISSUE THREAD

**Issue by asieira** [kemra102/puppet-cloudwatchlogs#9]
I see on the documentation that the `streamname` parameter can be used to specify the stream name to use. But how do I specify the log group name?

**Comment by kemra102** [comment]
Currently the **log_group_name** is to the same name as the resource name itself, e.g. if you have:

```puppet
cloudwatchlogs::log { 'Messages':
  path => '/var/log/messages',
}
```

then the **log_group_name** will be set to **Messages**.

Unless there is a reason you might want to make this separately configurable I think the best course would be for me to update the docs to reflect this information.

**Comment by asieira** [comment]
Ok, that is a very sane default. However, not everyone will necessarily want to conform to that standard.

For example, unless I understand this incorrectly, the way the module currently works would prevent me from sending two different log files to the same Log Group, correct?

**Comment by kemra102** [comment]
That is correct

**Comment by asieira** [comment]
So I would consider this a valid reason for having the Log Group separately configurable. :)

Do you agree?

**Comment by kemra102** [comment]
Not something I would use but if you might have a use for it I'm happy to code it in. Just let me know if it's a feature you want and I'll take appropriate action.

**Comment by asieira** [comment]
I do, actually. 

My application uses spot instances and creates and destroys instances rather frequently, so having the default structure (Log Group = log file, Log Stream = instance ID) doesn't work that well. Instead, I'll add the instance ID to the log content itself in my application, and I'll use the Log Group and Log Streams for other classifications that better suit my needs.

Thank you very much for the wonderful module and the willingness to add this new feature! :+1:

**Comment by kemra102** [comment]
Latest release on the Forge includes the requested change. Any problems with it just log a new issue, many thanks.

**Comment by asieira** [comment]
:bow:
